# Generated by Django 6.0.3 on 2026-03-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField()),
                ('SName', models.CharField(max_length=30)),
                ('SClass', models.IntegerField()),
                ('SAddress', models.CharField(max_length=100)),
            ],
        ),
    ]
